
name: make-lint-and-test
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: installing dependencies
        run: |
          pip install poetry
          make install
      - name: Lint
        run: |
          make lint
      - name: Test
        run: |
          make test